interface = "eth0"
global_traffic_threshold = 500000
global_packets_threshold = 500000
ip_traffic_threshold = 150000
ip_packets_threshold = 50000
notification_traffic_threshold = 150000
notification_packets_threshold = 50000
ipblock_retry_ticks = 5*60*1000
notification_command = "./scripts/notificate \"%1%\" \"%2%\" &"
onblockip_command = "./scripts/ipblock block %1% &"
onunblockip_command = "./scripts/ipblock unblock %1% &"
network_uncompromise_ticks = 30
onnetwork_compromise_command = "./scripts/networkcompromise compromised &"
onnetwork_uncompromise_command = "./scripts/networkcompromise uncompromised &"
log="logs/ddos-monitor.log"
watchedips="configs/watchedips.xml"
notificationsubject="DDOS Monitor notification"
